name: Stratagem
options:
  bundleIdPrefix: com.stratagem
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  CODE_SIGN_STYLE: Automatic
  PRODUCT_NAME: Stratagem
  MARKETING_VERSION: "0.1"
  CURRENT_PROJECT_VERSION: "1"

targets:
  Stratagem:
    type: application
    platform: macOS
    sources:
      - Stratagem
    settings:
      CODE_SIGN_ENTITLEMENTS: Stratagem/Stratagem.entitlements
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
      INFOPLIST_KEY_CFBundleDisplayName: Stratagem
      INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026"

schemes:
  Stratagem:
    build:
      targets:
        Stratagem: all
    run:
      config: Debug
    archive:
      config: Release
