"""Report generation tool — create markdown and PPTX reports."""

from typing import Any
from pathlib import Path
from datetime import datetime

from claude_agent_sdk import tool


@tool(
    "create_report",
    "Generate a formatted report from structured sections. Outputs markdown (.md), PowerPoint (.pptx), Word (.docx), or HTML files.",
    {
        "type": "object",
        "properties": {
            "title": {"type": "string", "description": "Report title"},
            "sections": {
                "type": "array",
                "description": "Report sections with heading and content",
                "items": {
                    "type": "object",
                    "properties": {
                        "heading": {"type": "string"},
                        "content": {"type": "string"},
                        "level": {"type": "integer", "description": "Heading level 1-3", "default": 2},
                    },
                    "required": ["heading", "content"],
                },
            },
            "format": {"type": "string", "enum": ["markdown", "pptx", "html", "docx"], "default": "markdown"},
            "output_path": {"type": "string", "description": "Where to save the report"},
            "metadata": {
                "type": "object",
                "description": "Optional report metadata (author, date, subtitle)",
                "properties": {
                    "author": {"type": "string"},
                    "date": {"type": "string"},
                    "subtitle": {"type": "string"},
                },
            },
        },
        "required": ["title", "sections", "output_path"],
    },
)
async def create_report(args: dict[str, Any]) -> dict[str, Any]:
    title = args["title"]
    sections = args["sections"]
    fmt = args.get("format", "markdown")
    output_path = args["output_path"]
    metadata = args.get("metadata", {})

    # Ensure output directory exists
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    if fmt == "markdown":
        return _create_markdown_report(title, sections, output_path, metadata)
    elif fmt == "pptx":
        return _create_pptx_report(title, sections, output_path, metadata)
    elif fmt == "docx":
        return _create_docx_report(title, sections, output_path, metadata)
    elif fmt == "html":
        return _create_html_report(title, sections, output_path, metadata)
    else:
        return _error(f"Unsupported format: {fmt}")


def _register_artifact(output_path: str, fmt: str, title: str) -> None:
    """Best-effort artifact registration."""
    try:
        from stratagem.artifacts import register
        register(path=output_path, format=fmt, title=title, cwd=Path.cwd())
    except Exception:
        pass


def _create_markdown_report(title: str, sections: list[dict], output_path: str, metadata: dict) -> dict[str, Any]:
    lines: list[str] = []

    # Header
    lines.append(f"# {title}")
    if metadata.get("subtitle"):
        lines.append(f"### {metadata['subtitle']}")
    lines.append("")

    # Metadata
    meta_parts = []
    if metadata.get("author"):
        meta_parts.append(f"**Author**: {metadata['author']}")
    date_str = metadata.get("date", datetime.now().strftime("%Y-%m-%d"))
    meta_parts.append(f"**Date**: {date_str}")
    if meta_parts:
        lines.append(" | ".join(meta_parts))
        lines.append("")
        lines.append("---")
        lines.append("")

    # Sections
    for section in sections:
        heading = section["heading"]
        content = section["content"]
        level = section.get("level", 2)
        lines.append(f"{'#' * level} {heading}")
        lines.append("")
        lines.append(content)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by Stratagem on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

    text = "\n".join(lines)
    Path(output_path).write_text(text, encoding="utf-8")
    _register_artifact(output_path, "markdown", title)

    saved = Path(output_path).resolve()
    if not saved.exists():
        return _error(f"Save completed but file not found at: {saved}")
    size = saved.stat().st_size
    if size == 0:
        return _error(f"File created but is empty: {saved}")

    return {"content": [{"type": "text", "text": f"Report saved: {saved} ({size:,} bytes, {len(sections)} sections)"}]}


def _create_pptx_report(title: str, sections: list[dict], output_path: str, metadata: dict) -> dict[str, Any]:
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        return _error("python-pptx not installed. Run: pip install python-pptx")

    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    try:
        slide.placeholders[0].text = title
    except (KeyError, IndexError):
        pass  # Layout has no title placeholder
    subtitle_parts = []
    if metadata.get("subtitle"):
        subtitle_parts.append(metadata["subtitle"])
    if metadata.get("author"):
        subtitle_parts.append(metadata["author"])
    date_str = metadata.get("date", datetime.now().strftime("%Y-%m-%d"))
    subtitle_parts.append(date_str)
    try:
        slide.placeholders[1].text = " | ".join(subtitle_parts)
    except (KeyError, IndexError):
        pass  # Layout has no subtitle placeholder

    # Content slides
    for section in sections:
        heading = section["heading"]
        content = section["content"]

        slide = prs.slides.add_slide(prs.slide_layouts[1])  # Title and Content
        try:
            slide.placeholders[0].text = heading
        except (KeyError, IndexError):
            pass

        try:
            tf = slide.placeholders[1].text_frame
            # Split content into paragraphs
            paragraphs = content.split("\n")
            tf.text = ""
            first = True
            for para in paragraphs:
                para = para.strip()
                if not para:
                    continue
                # Strip markdown bullet markers
                para = para.lstrip("- •*")
                if first:
                    tf.text = para
                    first = False
                else:
                    p = tf.add_paragraph()
                    p.text = para
        except (KeyError, IndexError):
            pass  # Layout has no content placeholder

    prs.save(output_path)
    _register_artifact(output_path, "pptx", title)

    saved = Path(output_path).resolve()
    if not saved.exists():
        return _error(f"Save completed but file not found at: {saved}")
    size = saved.stat().st_size
    if size == 0:
        return _error(f"File created but is empty: {saved}")

    return {"content": [{"type": "text", "text": f"PPTX report saved: {saved} ({len(sections) + 1} slides, {size:,} bytes)"}]}


def _create_docx_report(title: str, sections: list[dict], output_path: str, metadata: dict) -> dict[str, Any]:
    try:
        from docx import Document
        from docx.shared import Pt
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        return _error("python-docx not installed. Run: pip install python-docx")

    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    meta_parts = []
    if metadata.get("author"):
        meta_parts.append(f"Author: {metadata['author']}")
    date_str = metadata.get("date", datetime.now().strftime("%Y-%m-%d"))
    meta_parts.append(f"Date: {date_str}")
    if metadata.get("subtitle"):
        meta_parts.append(metadata["subtitle"])
    if meta_parts:
        meta_para = doc.add_paragraph(" | ".join(meta_parts))
        meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in meta_para.runs:
            run.font.size = Pt(10)
            run.font.italic = True

    doc.add_paragraph("_" * 60)  # Horizontal rule

    # Sections
    for section in sections:
        heading = section["heading"]
        content = section["content"]
        level = min(section.get("level", 2), 4)  # DOCX supports levels 0-4

        doc.add_heading(heading, level=level)

        # Process content: detect bullet lists vs paragraphs
        for para_text in content.split("\n"):
            stripped = para_text.strip()
            if not stripped:
                continue
            if stripped.startswith("- ") or stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif len(stripped) > 1 and stripped[0].isdigit() and stripped[1] in ".)" :
                doc.add_paragraph(stripped[2:].strip(), style="List Number")
            else:
                doc.add_paragraph(stripped)

    # Footer
    doc.add_paragraph("_" * 60)
    footer = doc.add_paragraph(f"Generated by Stratagem on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer.runs:
        run.font.size = Pt(8)
        run.font.italic = True

    doc.save(output_path)
    _register_artifact(output_path, "docx", title)

    saved = Path(output_path).resolve()
    if not saved.exists():
        return _error(f"Save completed but file not found at: {saved}")
    size = saved.stat().st_size
    if size == 0:
        return _error(f"File created but is empty: {saved}")

    return {"content": [{"type": "text", "text": f"DOCX report saved: {saved} ({len(sections)} sections, {size:,} bytes)"}]}


def _create_html_report(title: str, sections: list[dict], output_path: str, metadata: dict) -> dict[str, Any]:
    date_str = metadata.get("date", datetime.now().strftime("%Y-%m-%d"))
    author = metadata.get("author", "")

    html_parts = [
        "<!DOCTYPE html>",
        "<html lang=\"en\">",
        "<head>",
        f"  <title>{_html_escape(title)}</title>",
        "  <meta charset=\"utf-8\">",
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        "  <style>",
        "    body { font-family: -apple-system, system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; line-height: 1.6; }",
        "    h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }",
        "    h2 { margin-top: 2rem; color: #2c3e50; }",
        "    .meta { color: #666; font-size: 0.9rem; margin-bottom: 2rem; }",
        "    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }",
        "    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }",
        "    th { background: #f5f5f5; }",
        "    blockquote { border-left: 3px solid #ccc; margin: 1rem 0; padding: 0.5rem 1rem; color: #555; }",
        "    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }",
        "    pre { background: #f4f4f4; padding: 1rem; border-radius: 4px; overflow-x: auto; }",
        "    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #999; font-size: 0.8rem; }",
        "  </style>",
        "</head>",
        "<body>",
        f"  <h1>{_html_escape(title)}</h1>",
    ]

    if author or date_str:
        html_parts.append(f"  <p class=\"meta\">{_html_escape(author)}{' | ' if author else ''}{_html_escape(date_str)}</p>")

    for section in sections:
        heading = section["heading"]
        content = section["content"]
        level = section.get("level", 2)
        html_parts.append(f"  <h{level}>{_html_escape(heading)}</h{level}>")
        # Convert content paragraphs to HTML
        for para in content.split("\n\n"):
            para = para.strip()
            if para:
                html_parts.append(f"  <p>{_html_escape(para)}</p>")

    html_parts.extend([
        f"  <div class=\"footer\">Generated by Stratagem on {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>",
        "</body>",
        "</html>",
    ])

    html_text = "\n".join(html_parts)
    Path(output_path).write_text(html_text, encoding="utf-8")
    _register_artifact(output_path, "html", title)

    saved = Path(output_path).resolve()
    if not saved.exists():
        return _error(f"Save completed but file not found at: {saved}")
    size = saved.stat().st_size
    if size == 0:
        return _error(f"File created but is empty: {saved}")

    return {"content": [{"type": "text", "text": f"HTML report saved: {saved} ({size:,} bytes)"}]}


def _html_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _error(msg: str) -> dict[str, Any]:
    return {"content": [{"type": "text", "text": f"Error: {msg}"}], "isError": True}
